name: Deploy to Server ITC

on:
  workflow_dispatch:
  push:
    branches:
      - deploy
jobs: 
  deploy:
    name: "\U0001F389 Deploy"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: "\U0001F4C2 Sync files"
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 186.30.166.150
        port: 2727
        username: soporte
        password: HD36I7NQ
        remote_path: /home/soporte/itc
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  
    - name: Directory Permissions
      run: chmod -R 777 storage main/bootstrap/cache

    - name: Copy .env
      run: php -r "file_exists('main/.env') || copy('main/.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate
